### ISSUE TITLE
charm / consumable timers overlap

### ISSUE THREAD

**Issue by ssjshields** [ssjshields/archetype#40]
![image](https://user-images.githubusercontent.com/88489119/235835205-0bed9468-292c-4246-a03a-4b8e29bc3be9.png)
since active-item-tl is part of the archetype customization framework, change may need to be in gfx and main widgets.

**Comment by realmadrid1809** [comment]
Redesigned this area completely and as a consequence fixed this bug

**Comment by ssjshields** [comment]
needs revisit, reverted change due to background not disappearing with timer for some reason
