### ISSUE TITLE
The PC labels and equipment layout are wrong. 

### ISSUE THREAD

**Issue by xNeiKx** [ssjshields/archetype#41]
The PC labels and equipment layout are wrong. 
![errorPC](https://user-images.githubusercontent.com/132664365/236436812-76b5dc8a-3e54-40ed-9c22-a410cbf67acb.JPG)

**Comment by ssjshields** [comment]
We are aware.

Game just updated today.

**Comment by ssjshields** [comment]
fixed in 2f5e19e9b5bf6783af03ba7bbc8aebf57a6e78d1
