### ISSUE TITLE
PC Box

### ISSUE THREAD

**Issue by bobo6** [ssjshields/archetype#44]
Hi,

i played a little bit today an i saw the them ist a little bit wierd on the pc Box screen. So i change the theme back to normal an saw there was a rewrite from the dev for that. i put a picture for you in here. hope you can fix that.

Thanks for your great work. Love that theme alot

![image](https://github.com/ssjshields/archetype/assets/18252433/e2d8a33a-824e-4ef4-baf8-544c4f45ba6c)

**Comment by realmadrid1809** [comment]
Download the latest beta and follow all of the install instructions.

**Comment by ssjshields** [comment]
please download the latest beta, do not manually select the stable branch.

beta is the default branch, also you can see at the top of the branch GitHub automatically alerts you that changes have recently been made.

https://github.com/ssjshields/archetype

do not download the theme from other sources, like youtube videos or friends.
