### ISSUE TITLE
main.png overwritten by macOS Launcher

### ISSUE THREAD

**Issue by Kurtjwest** [ssjshields/archetype#46]
The PokeMMO macOS Launcher automatically updates and repairs the game files when booted, resulting in the archetype main.png being overwritten by the default one. 

Here is a copy of the log from the launcher:

Loading update feed..
Verifying game files..
Repairing the game files..
- data/sprites/atlas/main.png is invalid. Repairing..
Downloading..
- data/sprites/atlas/main.png downloading..
PokeMMO is installed!
Ready to run!

Not sure if this issue is fixable. Either way, thanks for your hard work on such an amazing theme!

**Comment by ssjshields** [comment]
Thanks for your report and feedback.

Might not be able to fix this one. A few months ago icons were moved from the theme's folder into the client's sprites folder.

Will look into a workaround.

**Comment by Seth-Revz** [comment]
There is a sh script in PokeMMO's main directory that will bypass the updater, unless there an actual update and the client sends you back :p
`/Users/<YOUR_USER>/Library/Application Support/com.pokeemu.macos/pokemmo-client-live/PokeMMO.sh`
Replace <YOUR_USER> with your username.

Make it executable with 
`chmod +x /Users/<YOUR_USER>/Library/Application Support/com.pokeemu.macos/pokemmo-client-live/PokeMMO.sh`
Create a new command file with the contents shown.

`pokemmo.command`
```sh
#!/bin/sh

cd /Users/<YOUR_USER>/Library/Application\ Support/com.pokeemu.macos/pokemmo-client-live
/Users/<YOUR_USER>/Library/Application Support/com.pokeemu.macos/pokemmo-client-live/PokeMMO.sh
```

Make it executable `chmod +x pokemmo.command`
I have no idea how to add this command file to the hotbar or application launcher cause I don't use a mac. But having it on the desktop to double click works fine.

**Comment by ssjshields** [comment]
no longer an issue now that themes are loaded into the game like mods 🥳
