### ISSUE TITLE
Polish diacritics

### ISSUE THREAD

**Issue by lui754** [ssjshields/archetype#48]
Hello,

Polish diacritics - Ą ą Ć Ę ę Ł ń ń Ó Ź ś Ź ź Ż ż

Polish diacritics are not displayed in your version of the theme. Is it possible to update the font to one that supports the above characters?

I solved this problem myself by updating the font from the website https://fonts.google.com/noto/specimen/Noto+Sans and replacing the font names with the .ttf extension in several files.

Many Polish players are abandoning your theme because of this error in displaying Polish characters.
It would be nice if you added this support in the next update.

Regards 
lui754 - Lukasz

(i use google translate)

**Comment by ssjshields** [comment]
@lui754 Thank you for the report, we will address this as soon as possible.

Can you confirm the default PokeMMO displays this text properly? Thanks

**Comment by lui754** [comment]
![archetype bez pl](https://github.com/ssjshields/archetype/assets/102246764/e3307ab5-a3b2-439e-83f7-69b509530dc1)
![default z pl](https://github.com/ssjshields/archetype/assets/102246764/ab1780ce-fff2-4743-93b5-1e2d6d18ec13)

I marked in red the places where, among other things, Polish characters are cut off.

Everything is fine on the default theme.
