### ISSUE TITLE
Iconos del chat duplicados

### ISSUE THREAD

**Issue by Thelperion** [ssjshields/archetype#52]
Los iconos de la ventada del chat se ven duplicados:

![Iconos duplicados 2023-10-02 152231](https://github.com/ssjshields/archetype/assets/38802801/a95f26f6-d879-487a-9498-028dae0a88d3)
[console.log](https://github.com/ssjshields/archetype/files/12782957/console.log)

**Comment by ssjshields** [comment]
@Thelperion Redownload the latest theme using incognito or clear your cookies and cache.

![image](https://github.com/ssjshields/archetype/assets/88489119/2d5fd784-3dd3-438f-a198-702b38ce0b81)

Bug is not present in latest version.

**Comment by ssjshields** [comment]
bug seems to originate on specific systems, possibly related to language.

![image](https://github.com/ssjshields/archetype/assets/88489119/a3805cb2-6e58-4351-9a77-c3a0c7f6f06c)

**Comment by ssjshields** [comment]
issue caused by missing default main.atlas file.
repair the PokeMMO client and reinstall main.png to resolve.
