### ISSUE TITLE
GTL, Advanced Search dosen't work

### ISSUE THREAD

**Issue by G3nn4ro** [ssjshields/archetype#53]
Hi guys, I would like to report a bug in the GTL. 
When you want to do an advanced search, with the new update of the game that they did yesterday, you will no longer see correctly the section "Advanced search" of the GTL.
Please solve this problem because without this theme, I cannot play!

![advanced search - default theme](https://github.com/ssjshields/archetype/assets/128425991/e9def5a9-e624-4734-94f7-7783c832e01a)
![advanced search](https://github.com/ssjshields/archetype/assets/128425991/e8a3dbf4-f906-407a-a129-d6104ea042ea)

**Comment by ssjshields** [comment]
@G3nn4ro Thanks for the report and interest in the theme.

I have a list of things that currently need to be address:

- GTL Advanced Search
- Instance screen
- PvP timers / check boxes
- Move Tutor
- Any other open GitHub issues

I compiled this list on our Discord, I am not entirely sure I will even open official issues for the other bugs, as we hopefully will have them fixed shortly.

If you come across any other issues, even if they are in the aforementioned list, don't hesitate to send them our way.

**Comment by ssjshields** [comment]
![advanced search](https://user-images.githubusercontent.com/128425991/276866133-e8a3dbf4-f906-407a-a129-d6104ea042ea.png)

Dig the color customization :)

**Comment by ssjshields** [comment]
fixed in fd95e5ca04557231af887244d54e82e3e14dec1a
