### ISSUE TITLE
add support for Billla's Automatic Encounter Counter

### ISSUE THREAD

**Issue by ssjshields** [ssjshields/archetype#56]
add option in customization xml or optional patch to re-add default HP bars to re-enable support for https://forums.pokemmo.com/index.php?/topic/66564-tool-automatic-encounter-counter-gen-5-support/

**Comment by realmadrid1809** [comment]
extract the folder inside this zip into the archetype folder. afterwards add this line to the theme.xml as the second to last line:
    <include filename="default_hp_bars/barcode.xml"/>

[default_hp_bars.zip](https://github.com/ssjshields/archetype/files/14338473/default_hp_bars.zip)
