### ISSUE TITLE
Unthemed tail on Unova dialogue box

### ISSUE THREAD

**Issue by gitnatel** [ssjshields/archetype#61]
Just this part of the dialogue box remains unthemed, been looking for a way to change it myself also.

![image](https://github.com/user-attachments/assets/beb79cb2-d3cf-4fc6-b2e3-783492a0bb04)

**Comment by ssjshields** [comment]
https://github.com/ssjshields/archetype/issues/2

**Comment by gitnatel** [comment]
ah right thanks
