### ISSUE TITLE
Interface problem after the Halloween update

### ISSUE THREAD

**Issue by G3nn4ro** [ssjshields/archetype#62]
Theme doesn't appear on setting menu --> interface after the Halloween event update.

Can is it fixable?

![theme problem](https://github.com/user-attachments/assets/0430fe07-fda2-4131-b7cf-dc7f4e4d9633)
![2 theme problem](https://github.com/user-attachments/assets/c77dfc1b-28f8-4c4a-bedc-04d92c8f4c74)
![3 theme problem](https://github.com/user-attachments/assets/5e4308f3-1731-4359-a42d-784b2effde6f)

**Comment by ssjshields** [comment]
Hi @G3nn4ro thanks for your report I will have a fix soon. Thank you

**Comment by ssjshields** [comment]
https://github.com/ssjshields/archetype/issues/63
