### ISSUE TITLE
27530 (Halloween 2024 update) fixes

### ISSUE THREAD

**Issue by ssjshields** [ssjshields/archetype#63]
todo
- [x] restructure mod directory, create new info file and icon
- [x] update old atlas (icon sheet.)
- [x] broker.xml
- [x] chat.xml
- [x] customization.xml
- [x] guild.xml
- [x] main.xml
- [x] misc.xml
- [x] monster-frame.xml
- [x] pc.xml
- [x] social.xml
- [x] staff.xml
- [x] gfx.xml
- [x] gfx_ui.xml
- [x] init.xml
- [x] main-widgets.xml
- [x] pokemmo_ui.png
- [x] user-interface.png

**Comment by KBQLgy** [comment]
Hello sir, I'm a fan from China and would like to ask how this theme has been used since the Halloween update

**Comment by KBQLgy** [comment]
![A6D9FAC8A1CDF6349779ABC9AA857F46](https://github.com/user-attachments/assets/bd156ae2-55cc-4fbd-b8e9-56f33dae723a)
Hello sir, I am a fan from China and would like to report the BUG, gender cannot be selected

**Comment by ssjshields** [comment]
Team log is also broken

**Comment by ssjshields** [comment]
Cannot release monsters

**Comment by ssjshields** [comment]
> Cannot release monsters

fixed

**Comment by ssjshields** [comment]
> Team log is also broken

fixed

**Comment by ssjshields** [comment]
![image](https://github.com/user-attachments/assets/78e133fd-9b61-4f34-afc1-27114f94078b)
check this label (SYS/ADMIN/GM, etc)

**Comment by ssjshields** [comment]
> ![image](https://private-user-images.githubusercontent.com/88489119/391800243-78e133fd-9b61-4f34-afc1-27114f94078b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Njg3ODIsIm5iZiI6MTczMzQ2ODQ4MiwicGF0aCI6Ii84ODQ4OTExOS8zOTE4MDAyNDMtNzhlMTMzZmQtOWI2MS00ZjM0LWFmYzEtMjcxMTRmOTQwNzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA3MDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZGUzYzc4NWUxNGZmZDI1ZmY4M2E0ZjRhMWEyMDVkYjQ5NjA3ZWU0ZTIwZTg0NjhlNDk4ZWY5MzFjMmYxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ImwxtVLlrc5XjQadaaw7k3ggc5GgBGY_SJbPoVFFRCw) check this label (SYS/ADMIN/GM, etc)

fixed https://github.com/ssjshields/archetype/commit/78548635355235713c9473fbe1ade724f847fe05
